from array import *

exchange_baseline = [
    ['最大的傳送大小－組織限制', '10240','Get-SendConnector "Connection to Contoso.com" | fl -property MaxMessageSize'],
    ['最大的接收大小(Mailbox)－連接器限制','10240','Get-TransportConfig | fl -property MaxReceiveSize'],
    ['啟用寄件者識別碼代理','TRUE', 'Set-SenderIDConfig | fl -property Enabled'],
    ['外部傳送連接器認證：DNS 路由', 'TRUE','Get-SendConnector "Connection to Contoso.com" | fl -property DNSRoutingEnabled'],
    ['設定寄件者篩選', 'TRUE','Get-SenderFilterConfig | fl -property Enabled'],
    ['啟用寄件者信譽', 'TRUE','Get-SenderReputationConfig | fl -property SenderBlockingEnabled'],
    ['限制每封郵件最多收件者人數－組織限制', 'TRUE','Get-TransportService -Identity "Server01" | fl -property PickupDirectoryMaxRecipientsPerMessage'],
    ['外部傳送連接器認證：忽略啟動TLS', 'TRUE','Get-SendConnector -identity <connector_name> | fl -property IgnoreSTARTTLS'],
    ['設定POP3的登入驗證', 'SecureLogin','Get-PopSettings | fl -property LoginType'],
    ['接收連接器：設定通訊協定記錄', 'Verbose','Get-ReceiveConnector "<IDENTITY>" | fl -property ProtocolLoggingLevel'],
    ['傳送連接器：設定通訊協定記錄', 'Verbose','Get-SendConnector "IDENTITY" | fl -property ProtocolLoggingLevel'],
    ['外部傳送連接器認證：網域安全', 'TRUE','get-sendconnector -Identity <SendConnectorIdParameter> | fl DomainSecureEnabled'],
    ['郵件追蹤記錄(Edge)', 'TRUE','Get-TransportService EXCHANGE1 | fl -property MessageTrackingLogEnabled'],
    # redundant ?
    ['郵件追蹤記錄(Mailbox)', 'TRUE','Get-TransportService EXCHANGE1 | fl -property MessageTrackingLogEnabled'],
    ['設定IMAP4的登入認證', 'SecureLogin','Get-ImapSettings | fl -property LoginType'],
    ['開啟連線記錄', 'TRUE','Get-TransportService EXCHANGE1 | fl -property ConnectivityLogEnabled'],
    ['最大的傳送大小(Mailbox )－組織限制', '10240KB','Get-TransportConfig | fl -property MaxSendSize'],
    ['最大的接收大小(Hub)－連接器限制', '10240KB','Get-ReceiveConnector "Connection from Contoso.com" | fl -property MaxMessageSize'],
    ['信箱配額：發出警告配額', '1991680KB','Get-MailboxDatabase "EXCHANGE01\Mailbox Database" | fl -property IssueWarningQuota'],
    ['信箱配額：禁止傳送與接收配額', '2411520KB','Get-MailboxDatabase "EXCHANGE01\Mailbox Database" | fl -property ProhibitSendReceiveQuota'],
    ['信箱配額：禁止傳送配額', '2097152KB','Get-MailboxDatabase "EXCHANGE01\Mailbox Database" | fl -property ProhibitSendQuota'],
    ['已刪除信箱之保留天數','30天','Get-Mailboxdatabase "EXCHANGE01\Mailbox Database" | fl -property MailboxRetention'],        
    ['在資料庫尚未備份前，需保留刪除的項目','TRUE','Get-MailboxDatabase <Mailbox Database Name> | fl -property RetainDeletedItemsUntilBackup'],
    ['允許簡單的密碼','FALSE','Get-MobileDeviceMailboxPolicy | fl -property AllowSimplePassword'],
    ['強制密碼歷程記錄','4個字元以上','Get-MobileDeviceMailboxPolicy | fl -property PasswordHistory'],
    ['密碼到期期限','90天以上','Get-MobileDeviceMailboxPolicy | fl -property PasswordExpiration'],
    ['最小密碼長度','4個字元以上','Get-MobileDeviceMailboxPolicy | fl -property MinPasswordLength'],
    ['設定啟動模式','TLS','Set-UMService -Identity Exchange1 -UMStartUpMode TLS'],
    ['設定重新整理間隔','1','Get-MobileDeviceMailboxPolicy -Identity default| fl -property -DevicePolicyRefreshInterval'],
    ['設定撥號對應表安全','Secured','Get-UMDialPlan -identity MySecureDialPlan | fl -property VoIPSecurity'],
    ['允許存取語音信箱不需要PIN','Get-UMMailboxPolicy -id MyUMMailboxPolicy | fl -property AllowPinlessVoiceMailAccess'],
    ['已刪除項目之保留天數','14天','Get-MailboxDatabase -Identity MDB2 | fl -property DeletedItemRetention'],
    ['允許非託管的裝置','FALSE','Get-MobileDeviceMailboxPolicy -Identity default | fl -property AllowNonProvisionableDevices'],
    ['需要加密裝置','TRUE','Get-MobileDeviceMailboxPolicy -Identity default | fl -property RequireDeviceEncryption'],
    ['超過閒置時間必須重新登入','15分鐘','Get-MobileDeviceMailboxPolicy -Identity Default | fl -property MaxInactivityTimeLock'],
    ['密碼需要字母與數字','TRUE','Get-MobileDeviceMailboxPolicy -Identity Default | fl -property AlphanumericPasswordRequired'],
    ['需要客戶端MAPI加密','TRUE','Get-RpcClientAccess | fl -property EncryptionRequired'],
    ['允許嘗試次數','10','Get-MobileDeviceMailboxPolicy -Identity Default | fl -property MaxPasswordFailedAttempts'],
    ['需要密碼','TRUE','Get-MobileDeviceMailboxPolicy -Identity Default | fl -property PasswordEnabled'],
    ['啟用系統管理員稽核記錄(UM)','TRUE','Get-AdminAuditLogConfig | fl -property AdminAuditLogCmdlets'],
    ['開啟腳本執行','TRUE','Get-ExecutionPolicy | fl -property RemoteSigned'],
    ['啟用系統管理員稽核記錄(CAS)','TRUE','Get-AdminAuditLogConfig | fl -property AdminAuditLogEnabled'],
    ['啟用自動回覆到遠端網域','TRUE','Get-RemoteDomain -Identity Contoso | fl -property AutoReplyEnabled'],
    ['允許基本認證','FALSE','Get-OwaVirtualDirectory -Identity "owa (Default Web Site)" | fl -property BasicAuthentication'],
    ['啟用未送達信件的報告到遠端網域','FALSE','Get-RemoteDomain -Identity Contoso | fl -property NDREnabled'],
    ['啟用外出回覆訊息到遠端網域','None','Get-RemoteDomain "RemoteDomain" | fl -property AllowedOOFType'],
    ['啟用自動轉寄到遠端網域','FALSE','Get-RemoteDomain -Identity Contoso | fl -property AutoForwardEnabled'],
    ['OWA 2013啟用S/MIME','TRUE','Get-OWAVirtualDirectory -identity "owa (Default Web Site)" | fl -property SMimeEnabled'],
    ['啟用系統管理員稽核記錄(Mailbox)','TRUE','Get-AdminAuditLogConfig | fl -property AdminAuditLogEnabled'],

]

def getBasline():
    return baseline