from array import *

gcb_baseline = [ 
    ['密碼最短使用期限', 'MinimumPasswordAge', 1, '?', '天'],
    ['密碼最長使用期限', 'MaximumPasswordAge', 90, '?',	'天'],
    ['最小密碼長度', 'MinimumPasswordLength', 12,'?','字元'],
    ['密碼必須符合複雜性需求', 'PasswordComplexity', 1,	'?', '停用/啟用'],
    ['強制執行密碼歷程記錄', 'PasswordHistorySize', 3,	'?', '代'],
    ['使用可還原的加密來存放密碼', 'ClearTextPassword',	0,	'?', '停用/啟用'],
    ['帳戶鎖定閾值', 'LockoutBadCount',	5, '?',	'次'],
    ['重設帳戶鎖定計數器的時間間隔', 'ResetLockoutCount', 15, '?', '分鐘'],
    ['帳戶鎖定期間', 'LockoutDuration',	15,	'?', '分鐘'],
    ['Microsoft網路用戶端：傳送未加密的密碼到其他廠商的SMB伺服器', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanmanWorkstation\Parameters\EnablePlainTextPassword',	0, 'REG_DWORD', '停用/啟用'],
    ['Microsoft網路用戶端：數位簽章用戶端的通訊(如果伺服器同意)', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanmanWorkstation\Parameters\EnableSecuritySignature', 1, 'REG_DWORD', '停用/啟用'],
    ['Microsoft網路用戶端：數位簽章用戶端的通訊(自動)',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanmanWorkstation\Parameters\RequireSecuritySignature', 1, 'REG_DWORD', '停用/啟用'],
    ['Microsoft網路伺服器：伺服器SPN目標名稱驗證層級', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanManServer\Parameters\SMBServerNameHardeningLevel', 0, 'REG_DWORD', '關閉/啟用'],
    ['Microsoft網路伺服器：數位簽章伺服器的通訊(自動)',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanManServer\Parameters\requiresecuritysignature', 1,	'REG_DWORD', '停用/啟用'],
    ['Microsoft網路伺服器：數位簽章伺服器的通訊(如果用戶端同意)',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanManServer\Parameters\enablesecuritysignature', 1, 'REG_DWORD','停用/啟用'],
    ['Microsoft網路伺服器：暫停工作階段前，要求的閒置時間',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanManServer\Parameters\autodisconnect', 15, 'REG_DWORD',	'分鐘'],
    ['Microsoft網路伺服器：當登入時數到期時，中斷用戶端連線', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanManServer\Parameters\enableforcedlogoff', 1, 'REG_DWORD', '停用/啟用'],
    ['MSS：(NoDefaultExempt) Configure IPSec exemptions for various types of network traffic.',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\IPSEC\NoDefaultExempt', 1, 'REG_DWORD', '值'],
    ['MSS：(KeepAliveTime) How often keep-alive packets are sent in milliseconds',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters\KeepAliveTime', 300000, 'REG_DWORD', '毫秒'],
    ['MSS：(TcpMaxDataRetransmissions) How many times unacknowledged data is retransmitted (3 recommended, 5 is default)', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters\TcpMaxDataRetransmissions', 3, 'REG_DWORD', '次'],
    ['MSS：(EnableICMPRedirect) Allow ICMP redirects to override OSPF generated routes', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters\EnableICMPRedirect', 1, 'REG_DWORD', '停用/啟用'],
    ['MSS：(Hidden) Hide Computer From the Browse List (not recommended except for highly secure environments)',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Lanmanserver\Parameters\Hidden',	1, 'REG_DWORD', '停用/啟用'],
    ['MSS：(DisableIPSourceRouting) IP source routing protection level (protects against packet spoofing)',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters\DisableIPSourceRouting',	2,'REG_DWORD', '值'],
    ['MSS：(DisableIPSourceRouting IPv6)IP source routing protection level(protects against packet spoofing)',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Tcpip6\Parameters\DisableIPSourceRouting',	2, 'REG_DWORD',	'值'],
    ['MSS：(NoNameReleaseOnDemand) Allow the computer to ignore NetBIOS name release requests except from WINS servers',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Netbt\Parameters\NoNameReleaseOnDemand', 1, 'REG_DWORD', '停用/啟用'],	
    ['MSS：(TcpMaxDataRetransmissions IPv6) How many times unacknowledged data is retransmitted (3 recommended, 5 is default)',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Tcpip6\Parameters\TcpMaxDataRetransmissions',	3,'REG_DWORD','次'],
    ['MSS：(PerformRouterDiscovery) Allow IRDP to detect and configure Default Gateway addresses (could lead to DoS)',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters\PerformRouterDiscovery',	1,'REG_DWORD', '停用/啟用'],	
    ['MSS：(AutoReboot) Allow Windows to automatically restart after a system crash (recommended except for highly secure environments)',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\CrashControl:AutoReboot', '?','?','?'],		
    ['MSS：(WarningLevel) Percentage threshold for the security event log at which the system will generate a warning',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Eventlog\Security\WarningLevel',	90,	'REG_DWORD', '值'],	
    ['MSS：(SafeDllSearchMode) Enable Safe DLL search mode (recommended)',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\SafeDllSearchMode',	1, 'REG_DWORD', '停用/啟用'],	
    ['MSS：(AutoAdminLogon) Enable Automatic Logon (not recommended)',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\AutoAdminLogon',	0,	'REG_DWORD', '停用/啟用'],	
    ['MSS：(AutoShareServer) Enable Administrative Shares (recommended except for highly secure environments)',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanmanServer\Parameters\AutoShareServer',	1,'REG_DWORD', '停用/啟用'],	
    ['MSS：(ScreenSaverGracePeriod) The time in seconds before the screen saver grace period expires (0 recommended)',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\ScreenSaverGracePeriod', 0, 'REG_DWORD', '值'],	
    ['互動式登入：在密碼到期前提示使用者變更密碼',	r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\passwordexpirywarning', 14, 'REG_DWORD',	'天'],
    ['互動式登入：要求網域控制站驗證以解除鎖定工作站',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\ForceUnlockLogon', 1, 'REG_DWORD',	'停用/啟用'],
    ['互動式登入：網域控制站無法使用時，要快取的先前登入次數', r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\cachedlogonscount', 0, 'REG_DWORD', '次'],
    ['互動式登入：智慧卡移除操作', r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\scremoveoption',	'1', 'REG_SZ',	'值'],
    ['互動式登入：須有智慧卡',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\scforceoption', 0,	'REG_DWORD', '停用/啟用'],
    ['互動式登入：不要求按CTRL+ALT+DEL鍵',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\DisableCAD', 0, 'REG_DWORD', '停用/啟用'],
    ['互動式登入：不要顯示上次登入的使用者名稱',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\DontDisplayLastUserName', 1,	'REG_DWORD', '停用/啟用'],
    ['系統加密編譯：對使用者儲存在電腦上的金鑰強制使用增強式金鑰保護',r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Cryptography\ForceKeyProtection', 0,	'REG_DWORD', '值'],
    ['系統加密編譯：使用FIPS 140相容加密演算法，包括加密、雜湊以及簽署演算法',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\FIPSAlgorithmPolicy\Enabled', 1, 'REG_DWORD', '停用/啟用'],
    ['系統物件：加強內部系統物件的預設權限(例如：符號連結)',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\ProtectionMode',	1,	'REG_DWORD', '停用/啟用'],
    ['系統物件：要求不區分大小寫用於非Windows子系統',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Kernel\ObCaseInsensitive', 1, 'REG_DWORD', '停用/啟用'],
    ['系統設定：選擇性的子系統',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\SubSystems\optional',	'Posix', 'REG_MULTI_SZ', 'Array'],
    ['系統設定：於軟體限制原則對Windows可執行檔使用憑證規則',r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\Safer\CodeIdentifiers\AuthenticodeEnabled', 1, 'REG_DWORD', '停用/啟用'],
    ['使用者帳戶控制：提示提升權限時切換到安全桌面',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\PromptOnSecureDesktop',	1,	'REG_DWORD', '停用/啟用'],
    ['使用者帳戶控制：允許UIAccess應用程式不使用安全桌面來提升權限',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\EnableUIADesktopToggle',	0, 'REG_DWORD', '停用/啟用'],
    ['使用者帳戶控制：在管理員核准模式，系統管理員之提升權限提示的行為',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\ConsentPromptBehaviorAdmin',	5, 'REG_DWORD','值'],	
    ['使用者帳戶控制：僅針對已簽署與驗證過的可執行檔，提高其權限',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\ValidateAdminCodeSignatures',	0, 'REG_DWORD', '停用/啟用'],
    ['使用者帳戶控制：所有系統管理員均以管理員核准模式執行',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\EnableLUA',	1, 'REG_DWORD',	'停用/啟用'],
    ['使用者帳戶控制：偵測應用程式安裝，並提示提升權限',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\EnableInstallerDetection', 1, 'REG_DWORD', '停用/啟用'],
    ['使用者帳戶控制：使用內建的Administrator帳戶的管理員核准模式',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\FilterAdministratorToken', 1,	'REG_DWORD', '停用/啟用'],
    ['使用者帳戶控制：標準使用者之提升權限提示的行為',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\ConsentPromptBehaviorUser', 3,	'REG_DWORD', '值'],	
    ['使用者帳戶控制：僅針對在安全位置安裝的UIAccess應用程式，提高其權限',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\EnableSecureUIAPaths',	1,	'REG_DWORD', '停用/啟用'],
    ['使用者帳戶控制：將檔案及登錄寫入失敗虛擬化並儲存至每一使用者位置',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\EnableVirtualization',	1,	'REG_DWORD','停用/啟用'],
    ['修復主控台：允許軟碟複製以及存取所有磁碟和所有資料夾',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole\setcommand', 0,'?', '停用/啟用'],	
    ['修復主控台：允許自動系統管理登入',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole\securitylevel',	0, '?',	'停用/啟用'],
    ['帳戶：限制使用空白密碼的本機帳戶僅能登入到主控台',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\LimitBlankPasswordUse',	1,	'REG_DWORD', '停用/啟用'],
    ['帳戶：重新命名來賓帳戶名稱','?','?','?','?'],	
    ['帳戶：重新命名系統管理員帳戶','(無)','y','?','?'],	
    ['裝置：防止使用者安裝印表機驅動程式',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Print\Providers\LanMan Print Services\Servers\AddPrinterDrivers', 1, 'REG_DWORD', '停用/啟用'],
    ['裝置：允許卸除而不須登入',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\undockwithoutlogon',	0, 'REG_DWORD',	'停用/啟用'],
    ['裝置：允許格式化以及退出卸除式媒體',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\AllocateDASD',	0,'REG_DWORD',	'值'],
    ['裝置：CD-ROM存取只限於登入本機的使用者',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\AllocateCDRoms',	0, 'REG_DWORD',	'停用/啟用'],
    ['裝置：軟碟機存取只限於登入本機的使用者',r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\AllocateFloppies',	0,	'REG_DWORD','停用/啟用'],
    ['網域成員：停用電腦帳戶密碼變更',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters\disablepasswordchange',	0,	'REG_DWORD', '停用/啟用'],
    ['網域成員：最長電腦帳戶密碼有效期',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters\maximumpasswordage',	30,	'REG_DWORD', '天'],
    ['網域成員：安全通道資料加以數位加密或簽章(自動)',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters\requiresignorseal',	1,	'REG_DWORD', '停用/啟用'],
    ['網域成員：安全通道資料加以數位簽章(可能的話)',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters\signsecurechannel',	1,	'REG_DWORD','停用/啟用'],
    ['網域成員：要求增強式(Windows 2000或更新)工作階段金鑰', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters\requirestrongkey',	1,	'REG_DWORD','停用/啟用'],
    ['網域成員：安全通道資料加以數位加密(可能的話)',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters\sealsecurechannel',	1,'REG_DWORD', '停用/啟用'],
    ['網域控制站：拒絕電腦帳戶密碼變更',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters\RefusePasswordChange',	0,	'REG_DWORD', '停用/啟用'],
    ['網域控制站：允許伺服器操作者排程工作',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\SubmitControl',	0,	'REG_DWORD', '停用/啟用'],
    ['網域控制站：LDAP伺服器簽章要求',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\NTDS\Parameters\ldapserverintegrity',	1,	'REG_DWORD', '停用/啟用'],
    ['網路存取：讓Everyone權限套用到匿名使用者',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\EveryoneIncludesAnonymous',	0,	'REG_DWORD', '停用/啟用'],
    ['網路存取：共用和安全性模式用於本機帳戶',r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\ForceGuest',	0, 'REG_DWORD',	'值'],
    ['網路存取：不允許SAM帳戶的匿名列舉',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\RestrictAnonymousSAM',	1,	'REG_DWORD','停用/啟用'],
    ['網路存取：限制匿名存取具名管道和共用',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanManServer\Parameters\restrictnullsessaccess',	1 ,'REG_DWORD',	'停用/啟用'],
    ['網路存取：可遠端存取的登錄路徑及子路徑',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\SecurePipeServers\Winreg\AllowedPaths\Machine', 
    r"""System\CurrentControlSet\Control\Print\Printers,System\CurrentControlSet\Services\Eventlog,Software\Microsoft\OLAP Server,Software\Microsoft\Windows NT\CurrentVersion\Print,Software\Microsoft\Windows NT\CurrentVersion\Windows,System\CurrentControlSet\Control\ContentIndex,System\CurrentControlSet\Control\Terminal Server,System\CurrentControlSet\Control\Terminal Server\UserConfig,System\CurrentControlSet\Control\Terminal Server\DefaultUserConfiguration,Software\Microsoft\Windows NT\CurrentVersion\Perflib,System\CurrentControlSet\Services\SysmonLog""",	'REG_MULTI_SZ', 'Array'],	
    ['網路存取：允許匿名SID/名稱轉譯',	r'LSAAnonymousNameLookup',	0,'?','值'],		
    ['網路存取：可以匿名存取的共用',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanManServer\Parameters\NullSessionShares' ,'?','REG_MULTI_SZ','Array'],	
    ['網路存取：可以匿名存取的具名管道',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanManServer\Parameters\NullSessionPipes','?', 'REG_MULTI_SZ', 'Array'],	
    ['網路存取：可遠端存取的登錄路徑',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\SecurePipeServers\Winreg\AllowedExactPaths\Machine',	r"""System\CurrentControlSet\Control\ProductOptions,System\CurrentControlSet\Control\Server Applications,Software\Microsoft\Windows NT\CurrentVersion""",'REG_MULTI_SZ', 'Array'],	
    ['網路存取：不允許存放網路驗證的密碼與認證',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\DisableDomainCreds',	0,	'REG_DWORD','停用/啟用'],
    ['網路存取：不允許SAM帳戶和共用的匿名列舉',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\RestrictAnonymous', 1, 'REG_DWORD', '停用/啟用'],
    ['網路安全性：下次密碼變更時不儲存LAN Manager雜湊數值',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\NoLMHash',	1,	'REG_DWORD','停用/啟用'],
    ['網路安全性：允許Local System對NTLM使用電腦身分識別',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\UseMachineId', 1,	'REG_DWORD', '停用/啟用'],
    ['網路安全性：LAN Manager驗證等級',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\LmCompatibilityLevel', 5,	'REG_DWORD', '值'],	
    ['網路安全性：允許對此電腦的PKU2U驗證要求使用線上身分識別',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\pku2u\AllowOnlineID',	0, 'REG_DWORD', '停用/啟用'],
    ['網路安全性：NTLM SSP為主的(包含安全RPC)伺服器的最小工作階段安全性', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\MSV1_0\NTLMMinServerSec', 537395200, 'REG_DWORD', '值'],
    ['網路安全性：允許LocalSystem NULL工作階段回復', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\MSV1_0\allownullsessionfallback', 0,	'REG_DWORD','停用/啟用'],
    ['網路安全性：NTLM SSP為主的(包含安全RPC)用戶端的最小工作階段安全性',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\MSV1_0\NTLMMinClientSec', 537395200,'REG_DWORD', '值'],
    ['網路安全性：設定Kerberos允許的加密類型',	r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters\SupportedEncryptionTypes',	2147483644,	'REG_DWORD','值'],
    ['網路安全性：LDAP用戶端簽章要求',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LDAP\LDAPClientIntegrity',	1,	'REG_DWORD', '停用/交涉簽章'],
    ['網路安全性：強制限制登入時數',	'(無)',	'M','?', '?'],	
    ['稽核：當無法記錄安全性稽核時，系統立即關機',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\crashonauditfail', 0,	'REG_DWORD', '停用/啟用'],
    ['稽核：稽核通用系統物件的存取',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\AuditBaseObjects', 0,	'REG_DWORD', '停用/啟用'],
    ['稽核：稽核備份與還原權限的使用',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\fullprivilegeauditing', 0 , 'REG_BINARY', '停用/啟用'],
    ['稽核：強制執行稽核原則子類別設定(WindowsVista或更新版本)以覆寫稽核原則類別設定',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa\scenoapplylegacyauditpolicy',	1,	'REG_DWORD', '停用/啟用'],
    ['關機：允許不登入就將系統關機', r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\ShutdownWithoutLogon', 0, 'REG_DWORD', '停用/啟用'],
    ['關機：清除虛擬記憶體分頁檔', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Memory Management\ClearPageFileAtShutdown', 0,'REG_DWORD', '停用/啟用'],
    ['鎖定記憶體中的分頁',	r'SeLockMemoryPrivilege', 'No One',	'?', 'SID'],
    ['增加處理程序工作組',	r'SeIncreaseWorkingSetPrivilege', '*S-1-5-19,*S-1-5-32-544', '?', 'SID'],
    ['關閉系統', 'SeShutdownPrivilege',	'*S-1-5-32-544', '?', 'SID'],
    ['調整處理程序的記憶體配額', 'SeIncreaseQuotaPrivilege', '*S-1-5-19,*S-1-5-20,*S-1-5-32-544' , '?', 'SID'],
    ['取代處理程序等級權杖', 'SeAssignPrimaryTokenPrivilege', '*S-1-5-19,*S-1-5-20', '?', 'SID'],
    ['取得檔案或其他物件的擁有權', 'SeTakeOwnershipPrivilege' ,'*S-1-5-32-544',	'?', 'SID'],
    ['拒絕透過遠端桌面服務登入', 'SeDenyRemoteInteractiveLogonRight', '*S-1-5-113,*S-1-5-32-546', '?',	'SID'],
    ['拒絕從網路存取這台電腦', 'SeDenyNetworkLogonRight' , '*S-1-5-114,*S-1-5-32-546', '?',	'SID'],
    ['載入及解除載入裝置驅動程式', 'SeLoadDriverPrivilege',	'*S-1-5-32-544',	'?', 'SID'],
    ['拒絕以服務方式登入',	'SeDenyServiceLogonRight', '*S-1-5-32-546',	'?', 'SID'],
    ['讓電腦及使用者帳戶受信賴，以進行委派', 'SeEnableDelegationPrivilege',	'No One', '?','SID'],
    ['備份檔案及目錄', 'SeBackupPrivilege',	'*S-1-5-32-544', '?','SID'],
    ['修改物件標籤', 'SeRelabelPrivilege',	'No One', '?', 'SID'],
    ['當成作業系統的一部分', 'SeTcbPrivilege', 'No One', '?', 'SID'],
    ['變更系統時間', 'SeSystemtimePrivilege', '*S-1-5-32-544,*S-1-5-19', '?', 'SID'],
    ['允許透過遠端桌面服務登入', 'SeRemoteInteractiveLogonRight', '*S-1-5-32-544', '?',	'SID'],
    ['修改韌體環境值', 'SeSystemEnvironmentPrivilege', '*S-1-5-32-544',	'?', 'SID'],
    ['建立通用物件', 'SeCreateGlobalPrivilege',	'*S-1-5-19,*S-1-5-20,*S-1-5-32-544,*S-1-5-6', '?',	'SID'],
    ['設定檔系統效能', 'SeSystemProfilePrivilege', '*S-1-5-32-544,*S-1-5-80-3139157870-2983391045-3678747466-658725712-1809340420',	'?', 'SID'],
    ['產生安全性稽核', 'SeAuditPrivilege',	'*S-1-5-19,*S-1-5-20',	'?', 'SID'],
    ['以服務方式登入',	'SeServiceLogonRight',	'No One', '?',	'SID'],
    ['存取認證管理員做為信任的呼叫者',	'SeTrustedCredManAccessPrivilege',	'No One', '?', 'SID'],
    ['變更時區', 'SeTimeZonePrivilege',	'*S-1-5-19,*S-1-5-32-544', '?', 'SID'],
    ['執行磁碟區維護工作',	'SeManageVolumePrivilege', '*S-1-5-32-544',	'?', 'SID'],
    ['建立權杖物件', 'SeCreateTokenPrivilege' , 'No One',	'?',	'SID'],
    ['強制從遠端系統進行關閉',	'SeRemoteShutdownPrivilege', '*S-1-5-32-544', '?', 'SID'],
    ['建立符號連結', 'SeCreateSymbolicLinkPrivilege', '*S-1-5-32-544', '?', 'SID'],
    ['從銜接站移除電腦', 'SeUndockPrivilege', '*S-1-5-32-544',	'?', 'SID'],
    ['略過周遊檢查', 'SeChangeNotifyPrivilege',	'*S-1-5-11,*S-1-5-19,*S-1-5-20,*S-1-5-32-544', '?',	'SID'],
    ['建立分頁檔',	'SeCreatePagefilePrivilege', '*S-1-5-32-544', '?', 'SID'],
    ['增加排程優先順序',  'SeIncreaseBasePriorityPrivilege', '*S-1-5-32-544', '?','SID'],
    ['將工作站新增至網域',	'SeMachineAccountPrivilege', '*S-1-5-32-544', '?', 'SID'],
    ['管理稽核及安全性記錄檔',	'SeSecurityPrivilege',	'*S-1-5-32-544','?', 'SID'],
    ['拒絕以批次工作登入',	'SeDenyBatchLogonRight', '*S-1-5-32-546', '?', 'SID'],
    ['同步處理目錄服務資料', 'SeSyncAgentPrivilege', 'No One',	'?', 'SID'],
    ['拒絕本機登入',	'SeDenyInteractiveLogonRight', '*S-1-5-32-546',	'?', 'SID'],
    ['偵錯程式',  'SeDebugPrivilege', '*S-1-5-32-544',	'?', 'SID'],
    ['建立永久共用物件', 'SeCreatePermanentPrivilege', 'No One', '?', 'SID'],
    ['還原檔案及目錄',	'SeRestorePrivilege', '*S-1-5-32-544',	'?', 'SID'],
    ['設定檔單一處理程序',	'SeProfileSingleProcessPrivilege' , '*S-1-5-32-544', '?', 'SID'],
    ['以批次工作登入',	'SeBatchLogonRight', '*S-1-5-32-544', '?',	'SID'],
    ['在驗證後模擬用戶端',	'SeImpersonatePrivilege', '*S-1-5-19,*S-1-5-20,*S-1-5-32-544,*S-1-5-6',	'?', 'SID'],
    ['從網路存取這台電腦',	'SeNetworkLogonRight', '*S-1-5-11,*S-1-5-32-544', '?', 'SID'],
    ['允許本機登入', 'SeInteractiveLogonRight',	'*S-1-5-32-544', '?', 'SID'],
    ['永遠以較高的特殊權限安裝', r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\Installer\AlwaysInstallElevated', 0,	'?', '停用/啟用'],	
    ['關閉自動播放', r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\NoDriveTypeAutoRun', 255,	'REG_DWORD', '值'],
    ['設定用戶端連線加密層級',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows NT\Terminal Services\MinEncryptionLevel', 3, 'REG_DWORD', '值'],
    ['安全性\保留舊事件',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\EventLog\Security\Retention', 0, 'REG_SZ',	'停用/啟用'],
    ['安全性\記錄檔大小上限(KB)', r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\EventLog\Security\MaxSize', 196608, 'REG_DWORD', 'KB'],
    ['系統\保留舊事件',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\EventLog\System\Retention', 0,	'REG_SZ', '停用/啟用'],
    ['系統\記錄檔大小上限(KB)',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\EventLog\System\MaxSize', 32768, 'REG_DWORD', 'KB'],
    ['應用程式\記錄檔大小上限(KB)',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\EventLog\Application\MaxSize',	32768,	'REG_DWORD', 'KB'],
    ['應用程式\保留舊事件',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\EventLog\Application\Retention', 0, 'REG_SZ', '停用/啟用'],
    ['Wired AutoConfig',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\dot3svc\Start', 3, 'REG_DWORD', '?'],	
    ['TPM Base Services',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TBS\Start',	'?', '?', '?'],	
    ['Diagnostic Policy Service',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\DPS\Start',	2,	'REG_DWORD', '?'],	
    ['Secondary Logon', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\seclogon\Start',	2,	'REG_DWORD', '?'],	
    ['Computer Browser', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\Browser\Start',	3,	'REG_DWORD', '?'],	
    ['SSDP Discovery',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\SSDPSRV\Start',	4,	'REG_DWORD', '?'],	
    ['PnP-X IP Bus Enumerator', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\IPBusEnum\Start', '?', '?',	'?'],
    ['Thread Ordering Server', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\THREADORDER\Start', 3,  'REG_DWORD', '?'],	
    ['Interactive Services Detection', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\UI0Detect\Start',	3,	'REG_DWORD', '?'],	
    ['Desktop Window Manager Session Manager', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\UxSms\Start',	'?', '?', '?'],	
    ['Network Location Awareness', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\NlaSvc\Start', 2,	'REG_DWORD', '?'],	
    ['Diagnostic Service Host', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\WdiServiceHost\Start',	3,	'REG_DWORD', '?'],	
    ['Windows Event Collector',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\Wecsvc\Start',	3,	'REG_DWORD', '?'],	
    ['Extensible Authentication Protocol', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\EapHost\Start',	3,	'REG_DWORD', '?'],	
    ['Print Spooler', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\Spooler\Start',	2,	'REG_DWORD', '?'],	
    ['Distributed Transaction Coordinator', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\MSDTC\Start', 2,	'REG_DWORD', '?'],	
    ['Microsoft Fibre Channel Platform Registration Service', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\FCRegSvc\Start', '?', '?', '?'],	
    ['User Profile Service', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\ProfSvc\Start',	2,	'REG_DWORD', '?'],	
    ['DNS Client',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\Dnscache\Start',	2,	'REG_DWORD', '值'],	
    ['Portable Device Enumerator Service', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\WPDBusEnum\Start', 3, 'REG_DWORD', '?'],	
    ['Smart Card', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\SCardSvr\Start',	3,	'REG_DWORD', '?'],	
    ['Windows Color System', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\WcsPlugInService\Start',	3,	'REG_DWORD', '?'],	
    ['Special Administration Console Helper', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\sacsvr\Start',	3, 'REG_DWORD', '?'],	
    ['Remote Access Connection Manager', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\RasMan\Start',	3,	'REG_DWORD', '?'],	
    ['Remote Access Auto Connection Manager', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\RasAuto\Start',	3,	'REG_DWORD', '?'],	
    ['Windows Modules Installer', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\TrustedInstaller\Start',	3,	'REG_DWORD', '?'],	
    ['Resultant Set of Policy Provider', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\RSoPProv\Start',	3,	'REG_DWORD', '?'],	
    ['Telephony', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\TapiSrv\Start',	3,	'REG_DWORD', '?'],	
    ['Windows Audio', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\AudioSrv\Start',	3,	'REG_DWORD', '?'],	
    ['IP Helper', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\iphlpsvc\Start',	2,	'REG_DWORD', '?'],	
    ['Remote Procedure Call (RPC) Locator',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\RpcLocator\Start',	3,	'REG_DWORD', '?'],	
    ['Windows Event Log', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\eventlog\Start',	2,	'REG_DWORD', '?'],	
    ['Problem Reports and Solutions Control Panel Support',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\wercplsupport\Start',	3,	'REG_DWORD', '?'],	
    ['Application Management',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\AppMgmt\Start',	3,	'REG_DWORD', '?'],	
    ['System Event Notification Service', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\SENS\Start',	2,	'REG_DWORD', '?'],	
    ['KtmRm for Distributed Transaction Coordinator', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\KtmRm\Start',	2,	'REG_DWORD', '?'],	
    ['Secure Socket Tunneling Protocol Service', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\SstpSvc\Start',	3,	'REG_DWORD', '?'],	
    ['CNG Key Isolation', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\KeyIso\Start',	3,	'REG_DWORD', '?'],	
    ['Remote Procedure Call (RPC)', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\RpcSs\Start',	2,	'REG_DWORD', '?'],	
    ['Power' , r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\Power\Start',	2,	'REG_DWORD', '?'],	
    ['Function Discovery Resource Publication',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\FDResPub\Start',	3,	'REG_DWORD', '?'],	
    ['Microsoft .NET Framework NGEN v2.0.50727_X86', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\clr_optimization_v2.0.50727_32\Start',	'?', '?', '?'],	
    ['Remote Desktop Configuration', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\SessionEnv\Start',	3,	'REG_DWORD', '?'],	
    ['Plug and Play', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\PlugPlay\Start',	2,	'REG_DWORD', '?'],	
    ['Smart Card Removal Policy', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\SCPolicySvc\Start',	3,	'REG_DWORD', '?'],	
    ['Routing and Remote Access', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\RemoteAccess\Start',	4,	'REG_DWORD', '?'],	
    ['Network Access Protection Agent',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\napagent\Start',	3,	'REG_DWORD', '?'],	
    ['Windows Update',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\wuauserv\Start',	2, 'REG_DWORD', '?'],	
    ['Volume Shadow Copy',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\VSS\Start',	3,	'REG_DWORD', '?'],	
    ['Network List Service', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\netprofm\Start', 2,	'REG_DWORD', '?'],	
    ['Windows Firewall', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\MpsSvc\Start',	2,	'REG_DWORD', '?'],	
    ['Microsoft iSCSI Initiator', r'Service	HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\MSiSCSI\Start', 3,  'REG_DWORD', '?'],	
    ['Application Experience',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\AeLookupSvc\Start',	2,	'REG_DWORD', '?'],	
    ['Application Layer Gateway Service', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\ALG\Start',	3,	'REG_DWORD', '?'],	
    ['Windows Audio Endpoint Builder', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\AudioEndpointBuilder\Start',	3,	'REG_DWORD', '?'],	
    ['ASP .NET State Service',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\aspnet_state\Start',	'?', '?', '?'],	
    ['Task Scheduler',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\Schedule\Start',	2,	'REG_DWORD', '?'],	
    ['Group Policy Client', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\gpsvc\Start', 2,	'REG_DWORD', '值'],	
    ['Health Key and Certificate Management', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\hkmsvc\Start',	3,	'REG_DWORD', '?'],	
    ['UPnP Device Host', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\upnphost\Start',	4,	'REG_DWORD', '?'],	
    ['Certificate Propagation', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\CertPropSvc\Start',	3,	'REG_DWORD', '?'],	
    ['Distributed Link Tracking Client', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\TrkWks\Start', 3, 'REG_DWORD', '值'],	
    ['Protected Storage', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\ProtectedStorage\Start',	'?', '?', '?'],	
    ['COM+ Event System', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\EventSystem\Start', 2,	'REG_DWORD', '?'],	
    ['Multimedia Class Scheduler',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\MMCSS\Start', 3,	'REG_DWORD', '?'],	
    ['Internet Connection Sharing (ICS)', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\SharedAccess\Start',	4,	'REG_DWORD', '?'],	
    ['Windows Driver Foundation - User-mode Driver Framework', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\wudfsvc\Start', 3, 'REG_DWORD','?'],	
    ['Workstation',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\LanmanWorkstation\Start',	2,	'REG_DWORD','值'],	
    ['Security Accounts Manager', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\SamSs\Start',	2,	'REG_DWORD','?'],	
    ['Windows Remote Management (WS-Management)', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\WinRM\Start',	2,	'REG_DWORD','?'],	
    ['Windows Time', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\W32Time\Start',	2,	'REG_DWORD','值'],	
    ['Windows Error Reporting Service',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\WerSvc\Start',	2,	'REG_DWORD','?'],	
    ['COM+ System Application',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\ComSysApp\Start',	3,	'REG_DWORD', '?'],	
    ['Virtual Disk', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\vds\Start',	3,	'REG_DWORD', '?'],
    ['Shell Hardware Detection', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\ShellHWDetection\Start', 2,	'REG_DWORD', '?'],	
    ['Function Discovery Provider Host', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\fdPHost\Start',	3,	'REG_DWORD', '?'],	
    ['Windows Management Instrumentation', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\Winmgmt\Start',	2,	'REG_DWORD', '?'],	
    ['Performance Logs & Alerts', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\pla\Start', 3,	'REG_DWORD', '?'],	
    ['IKE and AuthIP IPsec Keying Modules', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\IKEEXT\Start', '?', '?',	'?'],	
    ['Background Intelligent Transfer Service', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\BITS\Start',	3,	'REG_DWORD', '?'],	
    ['Network Connections',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\Netman\Start',	3,	'REG_DWORD', '?'],	
    ['Link-Layer Topology Discovery Mapper', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\lltdsvc\Start',	3,	'REG_DWORD', '?'],	
    ['Application Information',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\Appinfo\Start',	3,	'REG_DWORD', '?'],	
    ['WinHTTP Web Proxy Auto-Discovery Service', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\WinHttpAutoProxySvc\Start',	3,	'REG_DWORD', '?'],	
    ['WMI Performance Adapter', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\wmiApSrv\Start',	3,	'REG_DWORD', '?'],	
    ['DHCP Client', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\DHCP\Start',	2,	'REG_DWORD', '?'],	
    ['Microsoft Software Shadow Copy Provider', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\swprv\Start', 3,	'REG_DWORD', '?'],	
    ['Remote Registry', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\RemoteRegistry\Start', 2, 'REG_DWORD', '?'],	
    ['Server',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\LanmanServer\Start',	2,	'REG_DWORD', '值'],	
    ['DFS Replication', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\DFSR\Start',	2,	'REG_DWORD', '值'],	
    ['Windows Installer', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\msiserver\Start',	3,	'REG_DWORD', '?'],	
    ['Base Filtering Engine', r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\BFE\Start',	2,	'REG_DWORD', '?'],	
    ['Diagnostic System Host', 	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\WdiSystemHost\Start',	3,	'REG_DWORD', '?'],	
    ['Remote Desktop UserMode Port Redirector',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\UmRdpService\Start',	3,	'REG_DWORD', '?'],	
    ['DCOM Server Process Launcher',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\DcomLaunch\Start', '?',	'?', '?'],	

    ['Human Interface Device Access',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\hidserv\Start',	3,	'REG_DWORD', '?'],	
    ['Software Protection',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\sppsvc\Start',	2,	'REG_DWORD', '?'],	
    ['TCP/IP NetBIOS Helper',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\lmhosts\Start',	2,	'REG_DWORD', '?'],	
    ['Remote Desktop Services',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\TermService\Start',	2,	'REG_DWORD', '?'],	
    ['Cryptographic Services',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\CryptSvc\Start',	2,	'REG_DWORD', '?'],	
    ['Network Store Interface Service',	r'HKEY_LOCAL_MACHINE\System\CurrentControlSet\services\nsi\Start',	2,	'REG_DWORD', '?'],	
    ['稽核目錄服務變更', '目錄服務變更', '成功與失敗',	'?', 'Audit'],
    ['稽核詳細目錄服務複寫',	'詳細目錄服務複寫',	'沒有稽核',	'?', 'Audit'],
    ['稽核目錄服務複寫',	'目錄服務複寫',	'沒有稽核',	'?', 'Audit'],
    ['稽核目錄服務存取',	'目錄服務存取',	'成功與失敗', '?',	'Audit'],
    ['稽核系統完整性',	'系統完整性',	'成功與失敗',	'?', 'Audit'],
    ['稽核IPsec驅動程式',	'IPSEC driver',	'成功與失敗',	'?', 'Audit'],
    ['稽核安全性系統延伸',	'安全性系統延伸',	'成功與失敗',	'?', 'Audit'],
    ['稽核其他系統事件',	'其他系統事件',	'沒有稽核',	'?', 'Audit'],
    ['稽核安全性狀態變更',	'安全性狀態變更',	'成功與失敗',	'?',	'Audit'],
    ['稽核其他物件存取事件',	'其他物件存取事件',	'沒有稽核',	'?', 'Audit'],
    ['稽核控制代碼操作',	'控制代碼操作',	'沒有稽核',	'?', 'Audit'],
    ['稽核檔案共用', '檔案共用', '沒有稽核', '?',	'Audit'],
    ['稽核篩選平台連線',	'篩選平台連線',	'沒有稽核',	'?',	'Audit'],
    ['稽核憑證服務',	'憑證服務',	'沒有稽核',	'?',	'Audit'],
    ['稽核檔案系統',	'檔案系統',	'沒有稽核',	'?',	'Audit'],
    ['稽核SAM',	'SAM',	'沒有稽核',	'?',	'Audit'],
    ['稽核篩選平台封包丟棄',	'篩選平台封包丟棄',	'沒有稽核',	'?', 'Audit'],
    ['稽核產生的應用程式',	'產生的應用程式',	'沒有稽核',	'?', 'Audit'],
    ['稽核登錄', 'registry', '沒有稽核',	'?',	'Audit'],
    ['稽核詳細的檔案共用',	'詳細的檔案共用',	'沒有稽核',	'?',	'Audit'],
    ['稽核核心物件',	'核心物件',	'沒有稽核',	'?', 'Audit'],
    ['稽核篩選平台原則變更',	'篩選平台原則變更',	'沒有稽核',	'?', 'Audit'],
    ['稽核驗證原則變更',	'驗證原則變更',	 '成功',	'?',	'Audit'],
    ['稽核授權原則變更',	'授權原則變更',	'沒有稽核',	'?',	'Audit'],
    ['稽核「稽核原則變更」',	'稽核原則變更',	'成功與失敗',	'?',	'Audit'],
    ['稽核MPSSVC規則層級原則變更',	'MPSSVC 規則層級原則變更',	'沒有稽核',	'?', 'Audit'],
    ['稽核其他原則變更事件',	'其他原則變更事件',	'沒有稽核',	'?', 'Audit'],
    ['稽核機密特殊權限使用',	'機密特殊權限使用',	'成功與失敗',	'?',	'Audit'],
    ['稽核非機密特殊權限使用',	'非機密特殊權限使用',	'沒有稽核',	'?',	'Audit'],
    ['稽核其他特殊權限使用事件',	'其他特殊權限使用事件',	'沒有稽核',	'?', 'Audit'],
    ['稽核Kerberos驗證服務',	'Kerberos 驗證服務',	'沒有稽核',	'?',	'Audit'],
    ['稽核認證驗證', '認證驗證', '成功與失敗',	'?',	'Audit'],
    ['稽核Kerberos服務票證操作', 'Kerberos 服務票證操作', '沒有稽核', '?', 'Audit'],
    ['稽核其他帳戶登入事件', '其他帳戶登入事件', '沒有稽核', '?', 'Audit'],
    ['稽核應用程式群組管理', '應用程式群組管理', '沒有稽核', '?',	'Audit'],
    ['稽核電腦帳戶管理',	'Computer Account Management',	'成功與失敗',	'?', 'Audit'],
    ['稽核其他帳戶管理事件', '其他帳戶管理事件', '成功與失敗',	'?', 'Audit'],
    ['稽核安全性群組管理',	'安全性群組管理',	'成功與失敗',	'?', 'Audit'],
    ['稽核發佈群組管理',	'發佈群組管理',	'沒有稽核',	'?', 'Audit'],
    ['稽核使用者帳戶管理',	'使用者帳戶管理',	'成功與失敗',	'?', 'Audit'],
    ['稽核帳戶鎖定',	'帳戶鎖定',	'沒有稽核',	'?', 'Audit'],
    ['稽核IPsec延伸模式',	'IPsec 延伸模式', '沒有稽核', '?','Audit'],
    ['稽核網路原則伺服器',	'網路原則伺服器',	'成功',	'?', 'Audit'],
    ['稽核IPsec主要模式',	'IPsec 主要模式',	'沒有稽核',	'?', 'Audit'],
    ['稽核其他登入/登出事件',	'其他登入/登出事件',	'沒有稽核',	'?'	,'Audit'],
    ['稽核登出',	'登出',	'成功',	'?'	,'Audit'],
    ['稽核登入'	,'登入',	'成功與失敗',	'?'	,'Audit'],
    ['稽核IPsec快速模式	IPsec', '快速模式'	,'沒有稽核',	'?'	,'Audit'],
    ['稽核特殊登入'	,'特殊登入',	'成功',	'?'	,'Audit'],
    ['稽核RPC事件',	'RPC事件',	'沒有稽核',	'?'	,'Audit'],
    ['稽核DPAPI活動',	'DPAPI活動', '沒有稽核',	'?'	,'Audit'],
    ['稽核建立處理程序',	'建立處理程序',	'成功',	'?'	,'Audit'],
    ['稽核終止處理程序',	'終止處理程序',	'沒有稽核',	'?'	,'Audit'],
    ['帳戶：Administrator帳戶狀態',	'(無)'	,'已停用',	'?', '?'],
    ['帳戶：Guest帳戶狀態',	'(無)'	,'已停用', '?', '?'],
    ['Windows 防火牆: 網域設定檔: 輸出連線',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\DefaultOutboundAction',	0	,'REG_DWORD'	,'允許/封鎖'],
    ['Windows 防火牆: 網域設定檔: 防火牆狀態',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\EnableFirewall',	1	,'REG_DWORD'	,'停用/啟用'],
    ['Windows 防火牆: 網域設定檔: 輸入連線',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\DefaultInboundAction',	1	,'REG_DWORD'	,'允許/封鎖'],
    ['Windows 防火牆: 網域設定檔: 允許套用本機防火牆規則', 	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\AllowLocalPolicyMerge',	1	,'REG_DWORD'	,'否/是'],
    ['Windows 防火牆: 網域設定檔: 顯示通知',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\DisableNotifications',	1	,'REG_DWORD'	,'否/是'],
    ['Windows 防火牆: 網域設定檔: 允許套用本機連線安全性規則',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\AllowLocalIPsecPolicyMerge',	1	,'REG_DWORD'	,'否/是'],
    ['Windows 防火牆: 網域設定檔: 允許單點傳播回應',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\DomainProfile\DisableUnicastResponsesToMulticastBroadcast',	0	,'REG_DWORD'	,'否/是'],
    ['Windows 防火牆: 私人設定檔: 防火牆狀態',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\EnableFirewall',	1	,'REG_DWORD'	,'停用/啟用'],
    ['Windows 防火牆: 私人設定檔: 輸入連線',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\DefaultInboundAction',	1	,'REG_DWORD'	,'允許/封鎖'],
    ['Windows 防火牆: 私人設定檔: 允許套用本機防火牆規則',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\AllowLocalPolicyMerge',	1	,'REG_DWORD'	,'否/是'],
    ['Windows 防火牆: 私人設定檔: 顯示通知',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\DisableNotifications',	1	,'REG_DWORD'	,'否/是'],
    ['Windows 防火牆: 私人設定檔: 允許單點傳播回應', r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\DisableUnicastResponsesToMulticastBroadcast',	0	,'REG_DWORD'	,'否/是'],
    ['Windows 防火牆: 私人設定檔: 允許套用本機連線安全性規則',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\AllowLocalIPsecPolicyMerge',	1	,'REG_DWORD'	,'否/是'],
    ['Windows 防火牆: 私人設定檔: 輸出連線', r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\PrivateProfile\DefaultOutboundAction',	0	,'REG_DWORD'	,'允許/封鎖'],
    ['Windows 防火牆: 公用設定檔: 允許單點傳播回應',  r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\DisableUnicastResponsesToMulticastBroadcast',	0	,'REG_DWORD'	,'否/是'],
    ['Windows 防火牆: 公用設定檔: 顯示通知', r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\DisableNotifications',	1	,'REG_DWORD'	,'否/是'],
    ['Windows 防火牆: 公用設定檔: 允許套用本機連線安全性規則', 	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\AllowLocalIPsecPolicyMerge',	1	,'REG_DWORD'	,'否/是'],
    ['Windows 防火牆: 公用設定檔: 輸入連線', r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\DefaultInboundAction',	1	,'REG_DWORD'	,'允許/封鎖'],
    ['Windows 防火牆: 公用設定檔: 允許套用本機防火牆規則',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\AllowLocalPolicyMerge',	1	,'REG_DWORD'	,'否/是'],
    ['Windows 防火牆: 公用設定檔: 輸出連線', r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\DefaultOutboundAction',	0	,'REG_DWORD'	,'允許/封鎖'],
    ['Windows 防火牆: 公用設定檔: 防火牆狀態',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsFirewall\PublicProfile\EnableFirewall',	1	,'REG_DWORD'	,'停用/啟用'],
    ['互動式登入：電腦未使用時間限制', 	r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\InactivityTimeoutSecs',	900	, 'REG_DWORD',	'秒'],
    ['防止使用 OneDrive 儲存檔案',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\Skydrive\DisableFileSync',	1	,'REG_DWORD'	,'停用/啟用'],
    ['允許遠端殼層存取',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\WinRM\Service\WinRS\AllowRemoteShellAccess',	0	,'REG_DWORD'	,'停用/啟用'],
    ['系統起始的重新啟動之後自動登入最後一個互動式使用者',	r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\DisableAutomaticRestartSignOn',	1	,'REG_DWORD'	,'啟用/停用'],
    ['關閉市集應用程式',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsStore\RemoveWindowsStore',	1	,'REG_DWORD'	,'停用/啟用'],
    ['關閉自動下載和安裝更新',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsStore\AutoDownload',	4	,'REG_DWORD', '值'],
    ['關閉更新至最新版 Windows 的服務',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\WindowsStore\DisableOSUpgrade',	1	,'REG_DWORD','停用/啟用'],
    ['不要顯示網路選取UI',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\System\DontDisplayNetworkSelectionUI',	1	,'REG_DWORD'	,'停用/啟用'],
    ['在建立處理程序事件中包含命令列',	r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\Audit\ProcessCreationIncludeCmdLine_Enabled',	0	,'REG_DWORD'	,'停用/啟用'],
    ['允許加密檔案索引',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Search\AllowIndexingEncryptedStoresOrItems',	0	,'REG_DWORD'	,'停用/啟用'],
    ['設定 [搜尋] 中可以分享的資訊',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Search\ConnectedSearchPrivacy',	1	,'REG_DWORD'	,'停用/啟用'],
    ['允許選用Microsoft帳戶',	r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\MSAOptional',	1	,'REG_DWORD'	,'停用/啟用'],
    ['關閉Windows Messenger客戶經驗改進計畫',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Messenger\Client\CEIP',	2	,'REG_DWORD',	'值'],
    ['關閉搜尋小幫手內容檔更新',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\SearchCompanion\DisableContentFileUpdates',	1	,'REG_DWORD'	,'停用/啟用'],
    ['關閉檔案和資料夾的 [發佈到網站] 工作',	r'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\NoPublishingWizard',	1	,'REG_DWORD'	,'停用/啟用'],
    ['防止啟用鎖定畫面投影片放映',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\Personalization\NoLockScreenSlideshow',	1	,'REG_DWORD','停用/啟用'],
    ['防止啟用鎖定畫面相機',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\Personalization\NoLockScreenCamera',	1	,'REG_DWORD' ,'停用/啟用'],
    ['Active Directory Domain Services',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\NTDS\Start',	2,	'REG_DWORD', '值'],
    ['Active Directory Web Services',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\ADWS\Start',	2,	'REG_DWORD', '值'],
    ['Application Identity',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\AppIDSvc\Start',	2,	'REG_DWORD', '值'],
    ['DFS Namespace',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dfs\Start', 2,	'REG_DWORD','值'],
    ['DNS Server',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\DNS\Start', 2,	'REG_DWORD', '值'],
    ['File Replication',r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\NtFrs\Start',	4,	'REG_DWORD', '值'],
    ['Intersite Messaging',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\IsmServ\Start',	2,	'REG_DWORD', '值'],
    ['Kerberos Key Distribution Center',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\kdc\Start',	2,	'REG_DWORD', '值'],
    ['Netlogon',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Netlogon\Start', 2, 'REG_DWORD', '值'],
    ['防止下載隨函附件',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Internet Explorer\Feeds\DisableEnclosureDownload',	1,	'REG_DWORD', '停用/啟用'],
    ['加入 Microsoft MAPS',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\SpyNet\SpyNetReporting', 0,	'?', '停用/啟用'],
    ['允許使用者控制安裝',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Installer\EnableUserControl', 0,	'REG_DWORD', '停用/啟用'],
    ['防止出現 Windows Installer 指令碼的 Internet Explorer 安全性提示', 	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Installer\SafeForScripting',	0,	'REG_DWORD'	,'停用/啟用'],
    ['不允許摘要式驗證',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client\AllowDigest',	0,	'REG_DWORD'	,'停用/啟用'],
    ['允許未加密的流量',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client\AllowUnencryptedTraffic',	0,	'REG_DWORD'	,'停用/啟用'],
    ['允許基本驗證',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client\AllowBasic',	0,	'REG_DWORD', '停用/啟用'],
    ['不允許 WinRM 儲存 RunAs 認證',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service\DisableRunAs',	1,	'REG_DWORD'	,'停用/啟用'],
    ['允許未加密的流量',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service\AllowUnencryptedTraffic',	0,	'REG_DWORD'	,'停用/啟用'],
    ['允許基本驗證',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service\AllowBasic',	0	,'REG_DWORD'	,'停用/啟用'],
    ['不允許非磁碟區裝置的自動播放',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Explorer\NoAutoplayfornonVolume',	1,	'REG_DWORD'	,'停用/啟用'],
    ['設定 AutoRun 的預設行為',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\NoAutorun',	1, '?', 	'值'],
    ['關閉定位',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LocationAndSensors\DisableLocation',	1,	'REG_DWORD'	,'停用/啟用'],
    ['不要顯示密碼顯示按鈕',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\CredUI\DisablePasswordReveal',	1,	'REG_DWORD'	,'停用/啟用'],
    ['提升權限時列舉系統管理員帳戶',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\CredUI\EnumerateAdministrators',	0	,'REG_DWORD'	,'停用/啟用'],
    ['連線時永遠提示密碼',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\fPromptForPassword',	1	,'REG_DWORD'	,'停用/啟用'],
    ['需要安全的 RPC 通訊',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\fEncryptRPCTraffic',	1	,'REG_DWORD'	,'停用/啟用'],
    ['不允許磁碟重新導向',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\fDisableCdm',	1,	'REG_DWORD'	,'停用/啟用'],
    ['不要使用每一工作階段的暫存資料夾',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\PerSessionTempDir',	1,	'REG_DWORD'	,'啟用/停用'],
    ['結束後不刪除暫存資料夾',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\DeleteTempDirsOnExit',	1	,'REG_DWORD'	,'啟用/停用'],
    ['不允許儲存密碼',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\DisablePasswordSaving',	1	,'REG_DWORD'	,'停用/啟用'],
    ['設定 Windows SmartScreen 篩選工具',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System\EnableSmartScreen',	2,	'REG_DWORD', '值'],
    ['損毀時關閉終止堆集',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Explorer\NoHeapTerminationOnCorruption',	0,	'REG_DWORD'	,'停用/啟用'],
    ['關閉殼層通訊協定受保護模式',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\PreXPSP2ShellProtocolBehavior',	0,	'REG_DWORD'	,'停用/啟用'],
    ['關閉檔案總管的資料執行防止',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Explorer\NoDataExecutionPrevention'	,0	,'REG_DWORD'	,'停用/啟用'],
    ['列舉加入網域電腦上的本機使用者',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System\EnumerateLocalUsers',	0,	'REG_DWORD'	,'停用/啟用'],
    ['關閉鎖定畫面上的應用程式通知',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System\DisableLockScreenAppNotifications',	1,	'REG_DWORD'	,'停用/啟用'],
    ['開機啟動驅動程式初始化原則',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Policies\EarlyLaunch\DriverLoadPolicy',	1	,'REG_DWORD'	,'值'],
    ['喚醒電腦時必須使用密碼 (一般電源)',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51\ACSettingIndex',	1,	'REG_DWORD'	,'停用/啟用'],
    ['喚醒電腦時必須使用密碼 (使用電池)',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51\DCSettingIndex',	1,	'REG_DWORD'	,'停用/啟用'],
    ['Microsoft 支援服務診斷工具: 開啟 MSDT 與支援提供者的互動式通訊',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\ScriptedDiagnosticsProvider\Policy\DisableQueryRemoteServer',	0, 'REG_DWORD'	,'停用/啟用'],
    ['啟用/停用 PerfTrack',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WDI\{9c5a40da-b965-4fc3-8781-88dd50a6299d}\ScenarioExecutionEnabled', 0, '?', '停用/啟用'],
    ['關閉 HTTP 上的列印',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Printers\DisableHTTPPrinting',	1,	'REG_DWORD','停用/啟用'],
    ['關閉 Windows客戶經驗改進計畫',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\SQMClient\Windows\CEIPEnabl', 1,	'?', '停用/啟用'],
    ['關閉手寫辨識錯誤報告',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\HandwritingErrorReports\PreventHandwritingErrorReports',	1,	'REG_DWORD', '停用/啟用'],
    ['關閉市集的存取權',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Explorer\NoUseStoreOpenWith',	1,	'REG_DWORD',	'停用/啟用'],
    ['關閉透過 HTTP 下載印表機驅動程式',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Printers\DisableWebPnPDownload',	1,	'REG_DWORD', '停用/啟用'],
    ['設定提供遠端協助',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\fAllowUnsolicited',	0	,'REG_DWORD', '停用/啟用'],
    ['設定請求遠端協助',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\fAllowToGetHelp',	0,	'REG_DWORD', '停用/啟用'],
    ['關閉 Microsoft 對等網路服務',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Peernet\Disabled',	1	,'REG_DWORD',	'停用/啟用'],
    ['使用 Windows Connect Now 進行無線設定',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WCN\Registrars\EnableRegistrars HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WCN\Registrars\DisableUPnPRegistrar HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WCN\Registrars\DisableInBand802DOT11Registrar HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WCN\Registrars\DisableFlashConfigRegistrar HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WCN\Registrars\DisableWPDRegistrar',	0, '?','停用/啟用'],
    ['禁止存取 Windows Connect Now 精靈',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WCN\UI\DisableWcnUi',	1, '?', '停用/啟用'],	
    ['開啟 Mapper I/O (LLTDIO) 驅動程式',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LLTD\AllowLLTDIOOnDomain HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LLTD\AllowLLTDIOOnPublicNet HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LLTD\EnableLLTDIO HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LLTD\ProhibitLLTDIOOnPrivateNet' , 0, '?', '停用/啟用'],	
    ['開啟 Responder (RSPNDR) 驅動程式',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LLTD\AllowRspndrOnDomain HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LLTD\AllowRspndrOnPublicNet HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LLTD\EnableRspndr HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\LLTD\ProhibitRspndrOnPrivateNet' , 0, '?', '停用/啟用'],	
    ['要求網域使用者在設定網路的位置時必須提升權限',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Network Connections\NC_StdDomainUserSetLocation',	1,	'REG_DWORD','停用/啟用'],	
    ['禁止在您的 DNS 網域網路上安裝、設定及使用網路橋接', r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Network Connections\NC_AllowNetBridge_NLA',	1,	'REG_DWORD', '停用/啟用'],	
    ['在鎖定畫面上關閉快顯通知',	r'HKEY_USERS\[USER SID]\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\PushNotifications\NoToastApplicationNotificationOnLockScreen',	1, '?', '停用/啟用'],	
    ['防止轉碼器下載',	r'HKEY_USERS\[USER SID]\SOFTWARE\Policies\Microsoft\WindowsMediaPlayer\PreventCodecDownload', 1,'?', '停用/啟用'],	
    ['不要保留檔案附件的區域資訊',	r'HKEY_USERS\[USER SID]\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Attachments\SaveZoneInformation', 0, '?', '停用/啟用'],	
    ['開啟附件時通知防毒程式',	r'HKEY_USERS\[USER SID]\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Attachments\ScanWithAntiVirus',	1, '?', '停用/啟用'],	
    ['防止使用者共用其設定檔內的檔案',	r'HKEY_USERS\[USER SID]\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\NoInplaceSharing',	1, '?', '停用/啟用'],	
    ['以密碼保護螢幕保護裝置',	r'HKEY_USERS\[USER SID]\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop\ScreenSaverIsSecure',	1, '?','停用/啟用'],	
    ['啟用螢幕保護裝置',	r'HKEY_USERS\[USER SID]\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop\ScreenSaveActive',	1, '?', '停用/啟用'],	
    ['強制特定螢幕保護裝置',	r'HKEY_USERS\[USER SID]\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop\SCRNSAVE.EXE',  1, '?', '停用/啟用'],	
    ['Background Tasks Infrastructure Service',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\BrokerInfrastructure\Start',	2,	'REG_DWORD', '?'],	
    ['Credential Manager',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\VaultSvc\Start',	3,	'REG_DWORD', '?'],	
    ['Device Association Service',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\DeviceAssociationService\Start',	3,	'REG_DWORD', '?'],	
    ['Device Install Service',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\DeviceInstall\Start',	3,	'REG_DWORD', '?'],	
    ['Device Setup Manager',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\DsmSvc\Start',	3,	'REG_DWORD', '?'],	
    ['Encrypting File System (EFS)',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\EFS\Start',	3,	'REG_DWORD', '?'],	
    ['Hyper-V Data Exchange Service',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\vmickvpexchange\Start',	3,	'REG_DWORD', '?'],	
    ['Hyper-V Guest Shutdown Service',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\vmicshutdown\Start',	3,	'REG_DWORD', '?'],	
    ['Hyper-V Heartbeat Service',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\vmicheartbeat\Start',	3,	'REG_DWORD', '?'],	
    ['Hyper-V Remote Desktop Virtualization Service',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\vmicrdv\Start',	3,	'REG_DWORD', '?'],	
    ['Hyper-V Time Synchronization Service',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\vmictimesync\Start',	3	,'REG_DWORD', '?'],	
    ['Hyper-V Volume Shadow Copy Requestor',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\vmicvss\Start',	3,	'REG_DWORD', '?'],	
    ['IPsec Policy Agent',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\PolicyAgent\Start',	3,	'REG_DWORD', '?'],	
    ['KDC Proxy Server service (KPS)',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\KPSSVC\Start',	3,	'REG_DWORD', '?'],	
    ['Local Session Manager',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\LSM\Start',	2,	'REG_DWORD', '?'],	
    ['Net.Tcp Port Sharing Service',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\nettcpportsharing\Start',	4,	'REG_DWORD', '?'],	
    ['Network Connectivity Assistant',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\NcaSvc\Start',	3	,'REG_DWORD', '?'],	
    ['Optimize drives',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\defragsvc\Start',	3,	'REG_DWORD', '?'],	
    ['Performance Counter DLL Host',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\PerfHost\Start',	3,	'REG_DWORD', '?'],	
    ['Printer Extensions and Notifications',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\PrintNotify\Start',	3,	'REG_DWORD', '?'],	
    ['RPC Endpoint Mapper',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\RPCEptMapper\Start',	2,	'REG_DWORD', '?'],	
    ['SNMP Trap',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\SNMPTRAP\Start',	3	,'REG_DWORD', '?'],	
    ['Spot Verifier',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\svsvc\Start',	3,	'REG_DWORD', '?'],	
    ['Superfetch',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\SysMain\Start',	3,	'REG_DWORD','?'],	
    ['Themes',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Themes\Start',	2,	'REG_DWORD', '?'],	
    ['User Access Logging Service',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\UALSVC\Start',	2,	'REG_DWORD', '?'],	
    ['Windows All-User Install Agent',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\AllUserInstallAgent\Start',	'?',	'?', '?'],	
    ['Windows Font Cache Service',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\FontCache\Start',	2	,'REG_DWORD', '?'],	
    ['Windows Store Service (WSService)',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\WSService\Start',	3,	'REG_DWORD', '?'],	
    ['Data Deduplication Service',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\ddpsvc\Start',	'?', '?','?'],	
    ['Data Deduplication Volume Shadow Copy Service',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\ddpvssvc\Start',	'?', '?','?'],	
    ['File Server Resource Manager',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\srmsvc\Start',	'?', '?','?'],	
    ['File Server Storage Reports Manager',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\srmreports\Start',	'?', '?','?'],	
    ['Microsoft File Server Shadow Copy Agent Service',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\fssagent\Start',	'?', '?','?'],	
    ['Microsoft iSCSI Software Target',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\WinTarget\Start',	'?',	'?','?'],	
    ['Application Host Helper Service',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\apphostsvc\Start',	'?',	'?','?'],	
    ['Web Management Service',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\wmsvc\Start',	'?'	,'?','?'],	
    ['Windows Process Activation Service',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\was\Start',	'?',	'?','?'],	
    ['World Wide Web Publishing Service',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\w3svc\Start',	'?',	'?','?'],	
    ['Configure SMB v1 client driver',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\mrxsmb10\Start',	'?',	'?','?'],	
    ['Configure SMB v1 server',	r'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters\SMB1',	'?', '?', '?'],	
    ['封鎖未受信任的字型',	r'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\MitigationOptions\MitigationOptions_FontBocking',	'?','?', '?'],	
    ['啟用不安全的來賓登入',	r'HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\LanmanWorkstation\AllowInsecureGuestAuth',	'?', '?',	'?'],
]
    
def getBaseline():
    return gcb_baseline
    
    
    